// <auto-generated />
using System;
using EnmyAuto.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnmyAuto.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511064248_AddUserAuth")]
    partial class AddUserAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnmyAuto.Api.Models.AutoPostCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StoryboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("storyboard_id");

                    b.Property<Guid>("TikTokAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("tiktok_account_id");

                    b.Property<string>("TikTokVideoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tiktok_video_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_auto_post_campaigns");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_campaigns_status");

                    b.HasIndex("StoryboardId")
                        .HasDatabaseName("ix_auto_post_campaigns_storyboard_id");

                    b.HasIndex("TikTokAccountId", "ScheduledTime")
                        .HasDatabaseName("ix_campaigns_account_scheduled");

                    b.ToTable("auto_post_campaigns", (string)null);
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("file_url");

                    b.Property<Guid>("StoryboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("storyboard_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_media_assets");

                    b.HasIndex("StoryboardId", "Type")
                        .HasDatabaseName("ix_media_assets_storyboard_type");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.Storyboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ScriptJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("script_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_storyboards");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_storyboards_user_status");

                    b.ToTable("storyboards", (string)null);
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.TikTokAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("ShowcaseId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("showcase_id");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tiktok_accounts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tiktok_accounts_user_id");

                    b.ToTable("tiktok_accounts", (string)null);
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("QuotaLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("quota_limit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.AutoPostCampaign", b =>
                {
                    b.HasOne("EnmyAuto.Api.Models.Storyboard", "Storyboard")
                        .WithMany("AutoPostCampaigns")
                        .HasForeignKey("StoryboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_post_campaigns_storyboards_storyboard_id");

                    b.HasOne("EnmyAuto.Api.Models.TikTokAccount", "TikTokAccount")
                        .WithMany("AutoPostCampaigns")
                        .HasForeignKey("TikTokAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auto_post_campaigns_tiktok_accounts_tiktok_account_id");

                    b.Navigation("Storyboard");

                    b.Navigation("TikTokAccount");
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.MediaAsset", b =>
                {
                    b.HasOne("EnmyAuto.Api.Models.Storyboard", "Storyboard")
                        .WithMany("MediaAssets")
                        .HasForeignKey("StoryboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_assets_storyboards_storyboard_id");

                    b.Navigation("Storyboard");
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.Storyboard", b =>
                {
                    b.HasOne("EnmyAuto.Api.Models.User", "User")
                        .WithMany("Storyboards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storyboards_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.TikTokAccount", b =>
                {
                    b.HasOne("EnmyAuto.Api.Models.User", "User")
                        .WithMany("TikTokAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tiktok_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.Storyboard", b =>
                {
                    b.Navigation("AutoPostCampaigns");

                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.TikTokAccount", b =>
                {
                    b.Navigation("AutoPostCampaigns");
                });

            modelBuilder.Entity("EnmyAuto.Api.Models.User", b =>
                {
                    b.Navigation("Storyboards");

                    b.Navigation("TikTokAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
