using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EnmyAuto.Api.Enums;

namespace EnmyAuto.Api.Models;

[Table("storyboards")]
public class Storyboard
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    [Column("user_id")]
    public Guid UserId { get; set; }

    [Required]
    [MaxLength(300)]
    [Column("title")]
    public string Title { get; set; } = string.Empty;

    [Required]
    [Column("category")]
    public StoryboardCategory Category { get; set; }

    /// <summary>
    /// JSON payload holding scene-by-scene script generated by the AI pipeline.
    /// </summary>
    [Required]
    [Column("script_json", TypeName = "jsonb")]
    public string ScriptJson { get; set; } = "{}";

    [Required]
    [Column("status")]
    public StoryboardStatus Status { get; set; } = StoryboardStatus.Draft;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties
    [ForeignKey(nameof(UserId))]
    public User User { get; set; } = null!;

    public ICollection<MediaAsset> MediaAssets { get; set; } = [];
    public ICollection<AutoPostCampaign> AutoPostCampaigns { get; set; } = [];
}
